### ISSUE TITLE
Trouble with docker-in-docker proxy (?)

### ISSUE THREAD

**Issue by mlovci** [bgruening/galaxy-ipython#31]
Hello @bgruening and @jmchilton ... I'm trying to set up a galaxy server that runs IPython. I'm having a hard time getting things going, and was hoping for some advice on how to get moving.

I built the docker image with this Dockerfile and its friends in the same gist: `https://gist.github.com/mlovci/4bc35649bde8e6795a72`

`host$ cd docker_files/minimal`
`host$ docker build -t minimal .`
.... this builds in 3 minutes
`host$ docker run -it -P --privileged -v ${HOME}/instance_store/galaxy/:/export/ minimal bash`
`root@<container>$ /usr/bin/startup`
.... this takes  few moments to start and I'm able to view the galaxy cluster at `<IP>:<PORT>`, as expected. So far so good.
Then, I log in as admin and upload the test tab-delimited file I have in my gist. After it uploads I can click through `Visualize -> IPython` and I get a white screen on the browser.

Meanwhile, back in the terminal, I can watch the logs at `/home/galaxy/uwsgi.log` and it tells me that it's pulling `bgruening/docker-ipython-notebook` and after a bit, the new image shows with `root@<container>$ docker images`

For 60 seconds after the image finishes pulling, I can see that an ipython notebook process is running fine. And, if I expose the port that it is running on to the host, I can see the notebook dashboard.... it just doesn't display within the frame in galaxy.

I suspect there's something wrong with the way I set up the proxy handling, but I don't know enough about apache2 and galaxy at the same time to begin to fix this.

Can you bestow your knowledge?

Thank you,
Mike

**Comment by mlovci** [comment]
Unfortunately this is a problem again... but with new errors in the galaxy logs:

    ==> /var/log/supervisor/galaxy_nodejs_proxy-stdout---supervisor-S3UHGs.log <==  
    Proxy error:  { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }  
    Proxy error:  { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }  
    Proxy error:  { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }  
    ... repeats for umpteen seconds

Then:

    ==> /var/log/supervisor/docker-stdout---supervisor-bdgjrv.log <==
    time="2015-04-28T18:12:08Z" level="info" msg="+job log(die, e16562bdc33bafa937ec8082a98abc23b12a23f5af0d422c7bbeb89e6f2e52a5, bgruening/docker-ipython-notebook:latest)" 
    time="2015-04-28T18:12:08Z" level="info" msg="-job log(die, e16562bdc33bafa937ec8082a98abc23b12a23f5af0d422c7bbeb89e6f2e52a5, bgruening/docker-ipython-notebook:latest) = OK (0)" 
    time="2015-04-28T18:12:08Z" level="info" msg="+job release_interface(e16562bdc33bafa937ec8082a98abc23b12a23f5af0d422c7bbeb89e6f2e52a5)" 
    time="2015-04-28T18:12:08Z" level="info" msg="-job release_interface(e16562bdc33bafa937ec8082a98abc23b12a23f5af0d422c7bbeb89e6f2e52a5) = OK (0)" 

And a red flag pops up on the galaxy browser page:

    Error
    Could not connect to IE, contact your administrator


`docker port galaxy` shows:

    80/tcp -> 0.0.0.0:80
    8800/tcp -> 0.0.0.0:8800
    21/tcp -> 0.0.0.0:8021


and the ipython container logs show no unusual errors.

`dynamic_proxy_manage=True` in `galaxy.ini` and all the other parameters are default in that section.

Any thoughts on why this might be happening?

**Comment by mlovci** [comment]
Seems that there is discussion bewteen @jmchilton  and @bgruening here: https://github.com/bgruening/docker-galaxy-stable/issues/39

**Comment by mlovci** [comment]
@bgruening since this repo is deprecated, should I post this elsewhere?

**Comment by bgruening** [comment]
@mlovci it's ok here. I will try to look asap into it. For the time being have you tested the `bgruening/docker-ipython-notebook:0.2` image?

**Comment by mlovci** [comment]
@bgruening I had not tried that. I'm downloading it now.

**Comment by mlovci** [comment]
Well, that solved the problems in the galaxy logs... now the galaxy logs look like this:

    ==> /home/galaxy/uwsgi.log <==
    2c39150d5ac93c6e7da7a076ab13315ef6432614d5b73a2d403c2784a1250b8f
    172.17.42.1 - - [28/Apr/2015:23:50:19 +0000] "GET /visualization/show/ipython?dataset_id=1c9203a4ee99ff84 HTTP/1.1" 200 - "http://localhost:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
    [pid: 2076|app: 0|req: 195/412] 172.17.42.1 () {44 vars in 904 bytes} [Tue Apr 28 23:50:19 2015] GET /visualization/show/ipython?dataset_id=1c9203a4ee99ff84 => generated 1357 bytes in 2170 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 2)

    ==> /var/log/supervisor/docker-stdout---supervisor-bdgjrv.log <==
    time="2015-04-28T23:50:31Z" level="info" msg="+job log(die, 2c39150d5ac93c6e7da7a076ab13315ef6432614d5b73a2d403c2784a1250b8f, bgruening/docker-ipython-notebook:0.2)" 
    time="2015-04-28T23:50:31Z" level="info" msg="-job log(die, 2c39150d5ac93c6e7da7a076ab13315ef6432614d5b73a2d403c2784a1250b8f, bgruening/docker-ipython-notebook:0.2) = OK (0)" 
    time="2015-04-28T23:50:31Z" level="info" msg="+job release_interface(2c39150d5ac93c6e7da7a076ab13315ef6432614d5b73a2d403c2784a1250b8f)" 
    time="2015-04-28T23:50:31Z" level="info" msg="-job release_interface(2c39150d5ac93c6e7da7a076ab13315ef6432614d5b73a2d403c2784a1250b8f) = OK (0)" 


But, the ipython container logs have a new error:

    Traceback (most recent call last):
      File "/usr/local/bin/ipython", line 9, in <module>
        load_entry_point('ipython==2.3.0', 'console_scripts', 'ipython')()
      File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython
        return launch_new_instance(argv=argv, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 563, in launch_instance
        app.initialize(argv)
      File "<string>", line 2, in initialize
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 321, in initialize
        super(TerminalIPythonApp, self).initialize(argv)
      File "<string>", line 2, in initialize
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 381, in initialize
        self.parse_command_line(argv)
      File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
        return super(TerminalIPythonApp, self).parse_command_line(argv)
      File "<string>", line 2, in parse_command_line
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 475, in parse_command_line
        return self.initialize_subcommand(subc, subargv)
      File "<string>", line 2, in initialize_subcommand
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 413, in initialize_subcommand
        self.subapp.initialize(argv)
      File "<string>", line 2, in initialize
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 387, in initialize
        self.init_profile_dir()
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 295, in init_profile_dir
        p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
      File "/usr/local/lib/python2.7/dist-packages/IPython/utils/traitlets.py", line 342, in __get__
        value = method()
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 141, in _ipython_dir_default
        self._ipython_dir_changed('ipython_dir', d, d)
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 228, in _ipython_dir_changed
        shutil.copy(readme_src, readme)
      File "/usr/lib/python2.7/shutil.py", line 119, in copy
        copyfile(src, dst)
      File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
        with open(dst, 'wb') as fdst:
    IOError: [Errno 1] Operation not permitted: u'/ipython_setup/.ipython/README'

    If you suspect this is an IPython bug, please report it at:
        https://github.com/ipython/ipython/issues
    or send an email to the mailing list at ipython-dev@scipy.org

    You can print a more detailed traceback right now with "%tb", or use "%debug"
    to interactively debug it.

    Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
        c.Application.verbose_crash=True

    Traceback (most recent call last):
      File "/usr/local/bin/ipython", line 9, in <module>
        load_entry_point('ipython==2.3.0', 'console_scripts', 'ipython')()
      File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython
        return launch_new_instance(argv=argv, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 563, in launch_instance
        app.initialize(argv)
      File "<string>", line 2, in initialize
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 321, in initialize
        super(TerminalIPythonApp, self).initialize(argv)
      File "<string>", line 2, in initialize
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 381, in initialize
        self.parse_command_line(argv)
      File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
        return super(TerminalIPythonApp, self).parse_command_line(argv)
      File "<string>", line 2, in parse_command_line
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 475, in parse_command_line
        return self.initialize_subcommand(subc, subargv)
      File "<string>", line 2, in initialize_subcommand
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 413, in initialize_subcommand
        self.subapp.initialize(argv)
      File "<string>", line 2, in initialize
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/html/notebookapp.py", line 766, in initialize
        super(NotebookApp, self).initialize(argv)
      File "<string>", line 2, in initialize
      File "/usr/local/lib/python2.7/dist-packages/IPython/config/application.py", line 92, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 387, in initialize
        self.init_profile_dir()
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 295, in init_profile_dir
        p = ProfileDir.find_profile_dir_by_name(self.ipython_dir, self.profile, self.config)
      File "/usr/local/lib/python2.7/dist-packages/IPython/utils/traitlets.py", line 342, in __get__
        value = method()
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 141, in _ipython_dir_default
        self._ipython_dir_changed('ipython_dir', d, d)
      File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 228, in _ipython_dir_changed
        shutil.copy(readme_src, readme)
      File "/usr/lib/python2.7/shutil.py", line 119, in copy
        copyfile(src, dst)
      File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
        with open(dst, 'wb') as fdst:
    IOError: [Errno 1] Operation not permitted: u'/ipython_setup/.ipython/README'

    If you suspect this is an IPython bug, please report it at:
        https://github.com/ipython/ipython/issues
    or send an email to the mailing list at ipython-dev@scipy.org

    You can print a more detailed traceback right now with "%tb", or use "%debug"
    to interactively debug it.

    Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
        c.Application.verbose_crash=True

**Comment by mlovci** [comment]
(the second error is there twice because it appears in the log twice)

**Comment by mlovci** [comment]
By starting a container with `docker run -it bgruening/docker-ipython-notebook:0.2 bash` I can start `python`, but not `ipython`... I don't think it can write to `/ipython_setup` as the `nobody` user.

    root@19eda1f53143:/galaxy-central# docker run -it bgruening/docker-ipython-notebook:0.2 bash
    nobody@8a42b4bf30a8:/import$ cd /ipython_setup/.ipython/
    nobody@8a42b4bf30a8:~/.ipython$ ls -ltrha
    total 16K
    drwxrwxrwx 10 root root 4.0K Mar 12 13:50 ..
    drwxrwxrwx  4 root root 4.0K Mar 12 13:50 nbextensions
    drwxrwxrwx 11 root root 4.0K Mar 12 13:50 .
    drwxrwxrwx  9 root root 4.0K Mar 12 13:50 profile_default
    nobody@8a42b4bf30a8:~/.ipython$ ls -ltrha profile_default/
    total 20K
    -rwxrwxrwx  1 root root 1.3K Mar 12 13:12 ipython_notebook_config.py
    drwxrwxrwx 11 root root 4.0K Mar 12 13:50 ..
    drwxrwxrwx  6 root root 4.0K Mar 12 13:50 static
    drwxrwxrwx  2 root root 4.0K Mar 12 13:50 startup
    drwxrwxrwx  9 root root 4.0K Mar 12 13:50 .

**Comment by mlovci** [comment]
Just posting stream-of-consciousness as I find new things.

if I make an image (here called `ipy`) that switches user with this `Dockerfile`:
    
    FROM bgruening/docker-ipython-notebook:0.2
    USER root

then try IPython, it gets a little further;


    root@19eda1f53143:/export/ipy# docker run -it ipy ipython
    Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
    Type "copyright", "credits" or "license" for more information.

    IPython 2.3.0 -- An enhanced Interactive Python.

    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    ---------------------------------------------------------------------------
    IOError                                   Traceback (most recent call last)
    /ipython_setup/.ipython/profile_default/startup/00-load.py in <module>()
          1 from galaxy import get, put, get_galaxy_connection, _get_history_id
    ----> 2 HISTORY_ID = _get_history_id()

    /py/galaxy.py in _get_history_id()
         66 
         67 def _get_history_id():
    ---> 68     conf = _get_conf()
         69     return conf['history_id']
         70 

    /py/galaxy.py in _get_conf(config_file)
          9 
         10 def _get_conf( config_file = '/import/conf.yaml' ):
    ---> 11     with open(config_file, 'rb') as handle:
         12         conf = yaml.load(handle)
         13     return conf

    IOError: [Errno 2] No such file or directory: '/import/conf.yaml'
    In [1]: 

That looks like it would work if it were called with the proper `-v` parameter for `docker run`

**Comment by bgruening** [comment]
@mlovci are you using this image from within Galaxy? This `conf.yaml` is only created in the context of Galaxy. If so which Galaxy version you are using?

**Comment by mlovci** [comment]
Yes, I'm usually using this within galaxy. I was just testing with `docker run` whether I could get IPython started. I know that the container shouldn't be fully error-free without starting from galaxy. I think the problem with starting as a galaxy interactive viz is permissions for the `ipython_setup` directory.

**Comment by bgruening** [comment]
I have some fixes here pending: https://github.com/bgruening/docker-ipython-notebook/tree/uid_gid_changes

But with the `:0.2` version is should work with Galaxy. Currently, the master branch assumes wrongly that the user has some fixed uid/gid. Hope this branch can fix it.

**Comment by mlovci** [comment]
I'm OK with a fixed UID/GID ... I'm using an older `docker-galaxy-stable` image from you where the galaxy UID/GID is set to 451/450. Did you change that recently to 1450?

**Comment by bgruening** [comment]
2-4 month ago, yes. Oh I'm so bad in release management. Sorry!

**Comment by mlovci** [comment]
It's OK. Is there a protocol for updating the base docker image and all the galaxy file permissions without destroying things like toolsheds/config/postgres? I had extended your image with some goodies and I need to redo the `docker build` from this new image... I'm just worried about losing my environment.

**Comment by bgruening** [comment]
@mlovci keep a backup of the volume that is mounted under `/export` and you should be fine.
In theory starting a new docker container over an old `/export` should work. The only thing you need to take care of is the database migration.
I have filled an issue here to make this easier in the future: https://github.com/bgruening/docker-galaxy-stable/issues/53

**Comment by bgruening** [comment]
@mlovci we did a lot recently in Docker Galaxy land. I will close this please reopen an issue here: https://github.com/bgruening/docker-galaxy-stable/issues

**Comment by mlovci** [comment]
ok, thanks @bgruening
